name: Build and Test

on:
  push:
    branches:
      - master  # Триггер на пуши в ветку main
  pull_request:
    branches:
      - master  # Триггер на пул-реквесты в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонируем репозиторий

    - name: Setup .NET
      uses: actions/setup-dotnet@v3  # Устанавливаем .NET SDK
      with:
        dotnet-version: '7.0'  # Укажите версию .NET, которую используете

    - name: Restore dependencies
      run: dotnet restore  # Восстанавливаем зависимости

    - name: Build
      run: dotnet build --configuration Debug  # Собираем проект